### ISSUE TITLE
[Bug]: Multisig vulnerability by using wrong minSig value in generateMultiSigAddressFromAddresses

### ISSUE THREAD

**Issue by LouisLibre** [minotaur-ergo/minotaur-wallet#14]
The following file [action.ts line 352](https://github.com/minotaur-ergo/minotaur-wallet/blob/47f8810f72940a27990d0c6362b5278a5c82eadd/src/action/action.ts#L352) is calling **generateMultiSigAddressFromAddresses** with a wrong minSig value:
```js
const address = this.generateMultiSigAddressFromAddresses(
  pub_keys,
  parseInt(wallet.seed),
  getNetworkType(wallet.network_type)
);
```

As far as I'm concerned, ``wallet.seed`` does not contain the minimum number of signatures.

**generateMultiSigAddressFromAddresses** expects as parameter the minimum number of signatures to insert it into the ergo_tree which in turn generates the correct ergo address.

```js
generateMultiSigAddressFromAddresses = (
  publicKeys: Array<string>,
  minSig: number,
  network_type: NetworkType
){ 
  //... 
  ergoTree += '04' + int8_vlq(minSig);
  //...
}
```

Wheres the vulnerability?
- Sending the value `parseInt(wallet.seed)` to `int8_vlq` **will always return 1 as the minimum threshold**.
- parseInt(wallet.seed) -> NaN
- int8_vlq(NaN) -> 01

**Comment by vorujack** [comment]
In [action.ts line 589](https://github.com/minotaur-ergo/minotaur-wallet/blob/47f8810f72940a27990d0c6362b5278a5c82eadd/src/action/action.ts#L589) in multi-signature-wallet we store *minimum number of signatures* in seed column in database. So this problem does not exists.

**Comment by LouisSaberhagen** [comment]
IMO the problem still exists because of how it get's stored in the seed column

The function you pointed calls WalletDbAction.createWallet with `${minSig}` in the mnemonic parameter

```js
const createdWallet = await WalletDbAction.createWallet(
	name,
	WalletType.MultiSig,
	`${minSig}`,
	is_derivable ? wallet.extended_public_key : '',
	wallet.network_type
);
```

What happens when createWallet gets a minSig instead of a mnemonic?

```js
createWallet = async (
  name: string,
  type: WalletType,
  mnemonic: string,
  password: string,
  network_type: string,
  encryptionPassword: string
) => {
  const seed = mnemonicToSeedSync(mnemonic, password);
  const master = bip32.fromSeed(seed);
  const extended_public_key = master
    .derivePath(RootPathWithoutIndex)
    .neutered();
  const storedSeed = encryptionPassword
    ? encrypt(seed, encryptionPassword)
    : seed.toString('hex');
  const wallet = await WalletDbAction.createWallet(
    name,
    type,
    storedSeed,
    extended_public_key.toBase58(),
    network_type
  );
  await AddressAction.addWalletAddresses(wallet);
  store.dispatch({ type: actionTypes.INVALIDATE_WALLETS });
};
```

Let's answer the question by using a simultaed minSig value of 3:
```js
minSig = 3;
createWallet(...,...,`${minSig}`,....);
>  const seed = mnemonicToSeedSync(mnemonic, password);
    // const seed = mnemonicToSeedSync('3','')
    //  <Buffer e1 21 2f 57 81 c4 bb ff a5 e8 5d 42 d1 dd 3f 68 33 97 19 bd 38 46 22 81 5e f4 75 06 9d 92 22 51 5a d8 c0 a0 68 b3 e7 0d 26 89 35 3b 88 bd 17 a2 14 0f ... 14 more bytes>
>  const storedSeed = encryptionPassword  ? encrypt(seed, encryptionPassword)   : seed.toString('hex');
    // const storedSeed = false ? ... : seed.toString('hex');
    // 'e1212f5781c4bbffa5e85d42d1dd3f68339719bd384622815ef475069d9222515ad8c0a068b3e70d2689353b88bd17a2140fd79c09caaca638e46cf3ccd205fc'
```

So it will save that last hexadecimal string into disk. 

Whenever you try to read again via parseInt you will get the same problem, NaN and then 1 as the minimum threshold.

```js
// 'e1212f5781c4bbffa5e85d42d1dd3f68339719bd384622815ef475069d9222515ad8c0a068b3e70d2689353b88bd17a2140fd79c09caaca638e46cf3ccd205fc'
> parseInt(storedSeed)
// NaN
```

**Comment by LouisSaberhagen** [comment]
Correct, it seems minSig is being stored in disk directly as a String.

Funds are safu. 

- The vulnerability assumed that the seed parameter had a text value given the field type of seed.
- I would still advise to create a different column for minSig with a field of type Int (instead of text) so it can prevent future issues.
