### ISSUE TITLE
[Feature Request] - Multi-Sig communication

### ISSUE THREAD

**Issue by glasgowm148** [minotaur-ergo/minotaur-wallet#16]
Would be good to have a warning on the multi-sig communication page so you don't accidentally create a new commitment mid-signing. 

![Screenshot 2023-09-07 at 10 19 20](https://github.com/minotaur-ergo/minotaur-wallet/assets/19927264/2b7ab9e0-cf62-44fa-b0b1-250dc9018cd8)

Adding a paragraph here on when to use each button would greatly improve the UX, something like;

- UPDATE: Refreshes the saved state
- ⚠️ Ensure you don't use CREATE COMMITMENT at the wrong time as it will cause you to lose all progress

**Comment by vorujack** [comment]
Create Commitment can not called twice. 

Also in Minotaur-v2 these pages redesigned. Please check rc version released
