### ISSUE TITLE
Minotaur Wallet Setup 1.0.3 on Windows: Unhandled Error SQLITE_CANTOPEN: unable to open database file on install

### ISSUE THREAD

**Issue by cafebedouin** [minotaur-ergo/minotaur-wallet#5]

**Comment by minotaur-ergo** [comment]
can you send more log for this error?

**Comment by cafebedouin** [comment]
Windows 10 Pro. Build 19044.1586. 

I don't typically use Windows. So, I didn't know where to look for log information. I tried uninstalling and reinstalling, using the same exe file, and it worked after with no problems. So, maybe just some weird anomalous error?
